import type { TeamInfo } from '@/lib/types';

export const TEAMS: Record<string, TeamInfo> = {
  // ── Western Conference ──────────────────────────────────────────────
  OKC: {
    abbreviation: 'OKC',
    name: 'Thunder',
    city: 'Oklahoma City',
    color: '#007dc5',
    conference: 'west',
  },
  DEN: {
    abbreviation: 'DEN',
    name: 'Nuggets',
    city: 'Denver',
    color: '#0e2240',
    textColor: '#fdb927',
    conference: 'west',
  },
  MIN: {
    abbreviation: 'MIN',
    name: 'Timberwolves',
    city: 'Minnesota',
    color: '#0c2340',
    textColor: '#78be20',
    conference: 'west',
  },
  LAL: {
    abbreviation: 'LAL',
    name: 'Lakers',
    city: 'Los Angeles',
    color: '#552583',
    textColor: '#fdb927',
    conference: 'west',
  },
  HOU: {
    abbreviation: 'HOU',
    name: 'Rockets',
    city: 'Houston',
    color: '#ce1141',
    conference: 'west',
  },
  GSW: {
    abbreviation: 'GSW',
    name: 'Warriors',
    city: 'Golden State',
    color: '#006bb6',
    textColor: '#fdb927',
    conference: 'west',
  },
  MEM: {
    abbreviation: 'MEM',
    name: 'Grizzlies',
    city: 'Memphis',
    color: '#5d76a9',
    conference: 'west',
  },
  SAC: {
    abbreviation: 'SAC',
    name: 'Kings',
    city: 'Sacramento',
    color: '#5b2b82',
    conference: 'west',
  },
  DAL: {
    abbreviation: 'DAL',
    name: 'Mavericks',
    city: 'Dallas',
    color: '#00538c',
    conference: 'west',
  },
  PHX: {
    abbreviation: 'PHX',
    name: 'Suns',
    city: 'Phoenix',
    color: '#1d1160',
    textColor: '#e56020',
    conference: 'west',
  },
  LAC: {
    abbreviation: 'LAC',
    name: 'Clippers',
    city: 'Los Angeles',
    color: '#c8102e',
    conference: 'west',
  },
  NOP: {
    abbreviation: 'NOP',
    name: 'Pelicans',
    city: 'New Orleans',
    color: '#0c2340',
    textColor: '#c8102e',
    conference: 'west',
  },
  SAS: {
    abbreviation: 'SAS',
    name: 'Spurs',
    city: 'San Antonio',
    color: '#c4ced4',
    textColor: '#000000',
    conference: 'west',
  },
  POR: {
    abbreviation: 'POR',
    name: 'Trail Blazers',
    city: 'Portland',
    color: '#e03a3e',
    conference: 'west',
  },
  UTA: {
    abbreviation: 'UTA',
    name: 'Jazz',
    city: 'Utah',
    color: '#002b5c',
    textColor: '#00471b',
    conference: 'west',
  },

  // ── Eastern Conference ──────────────────────────────────────────────
  CLE: {
    abbreviation: 'CLE',
    name: 'Cavaliers',
    city: 'Cleveland',
    color: '#860038',
    textColor: '#fdbb30',
    conference: 'east',
  },
  MIA: {
    abbreviation: 'MIA',
    name: 'Heat',
    city: 'Miami',
    color: '#98002e',
    conference: 'east',
  },
  BOS: {
    abbreviation: 'BOS',
    name: 'Celtics',
    city: 'Boston',
    color: '#007a33',
    conference: 'east',
  },
  ORL: {
    abbreviation: 'ORL',
    name: 'Magic',
    city: 'Orlando',
    color: '#0077c0',
    conference: 'east',
  },
  NYK: {
    abbreviation: 'NYK',
    name: 'Knicks',
    city: 'New York',
    color: '#006bb6',
    textColor: '#f58426',
    conference: 'east',
  },
  DET: {
    abbreviation: 'DET',
    name: 'Pistons',
    city: 'Detroit',
    color: '#c8102e',
    textColor: '#1d428a',
    conference: 'east',
  },
  IND: {
    abbreviation: 'IND',
    name: 'Pacers',
    city: 'Indiana',
    color: '#002d62',
    textColor: '#fdbb30',
    conference: 'east',
  },
  MIL: {
    abbreviation: 'MIL',
    name: 'Bucks',
    city: 'Milwaukee',
    color: '#00471b',
    conference: 'east',
  },
  ATL: {
    abbreviation: 'ATL',
    name: 'Hawks',
    city: 'Atlanta',
    color: '#e03a3e',
    conference: 'east',
  },
  CHI: {
    abbreviation: 'CHI',
    name: 'Bulls',
    city: 'Chicago',
    color: '#ce1141',
    conference: 'east',
  },
  TOR: {
    abbreviation: 'TOR',
    name: 'Raptors',
    city: 'Toronto',
    color: '#ce1141',
    conference: 'east',
  },
  BKN: {
    abbreviation: 'BKN',
    name: 'Nets',
    city: 'Brooklyn',
    color: '#000000',
    conference: 'east',
  },
  PHI: {
    abbreviation: 'PHI',
    name: '76ers',
    city: 'Philadelphia',
    color: '#006bb6',
    textColor: '#ed174c',
    conference: 'east',
  },
  WAS: {
    abbreviation: 'WAS',
    name: 'Wizards',
    city: 'Washington',
    color: '#002b5c',
    textColor: '#e31837',
    conference: 'east',
  },
  CHA: {
    abbreviation: 'CHA',
    name: 'Hornets',
    city: 'Charlotte',
    color: '#1d1160',
    textColor: '#00788c',
    conference: 'east',
  },
};
